<a href="https://colab.research.google.com/github/fateme-alk/learning/blob/main/learning/IBM_data_analysis/module1/IBM_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/


In [ ]:
!pwd

/content


In [ ]:
!ls -al

total 20
drwxr-xr-x 1 root root 4096 Mar 30 14:42 .
drwxr-xr-x 1 root root 4096 Mar 30 14:41 ..
drwxr-xr-x 4 root root 4096 Mar 24 13:34 .config
drwx------ 6 root root 4096 Mar 30 14:42 drive
drwxr-xr-x 1 root root 4096 Mar 24 13:34 sample_data


In [ ]:
import os
os.chdir('drive/MyDrive/IBM-data-analysis/module1')

In [ ]:
!ls -al

total 2210
-rw------- 1 root root   24864 Mar  1 10:02  auto.csv
-rw------- 1 root root 1162326 Mar  3 04:38  Ex1.ipynb
-rw------- 1 root root   25861 Mar 26 06:40  export_auto.csv
-rw------- 1 root root 1048118 Mar 30 12:34 ' IBM_data_analysis_copy.ipynb'
-rw------- 1 root root     176 Mar 30 14:11 'Untitled document.gdoc'


In [ ]:
import pandas as pd
import numpy as np
import inspect

## import dataset

In [ ]:
url = "auto.csv"

In [ ]:
df = pd.read_csv(url)

## exports pandas data frame






In [ ]:
# exports pandas data frame  to a new CSV file named 'export_auto.csv in current working directory
export_path = "export_auto.csv"
df.to_csv(export_path)

In [ ]:
df

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19     3.4              10.0        102   
4            136         mpfi  3.19     3.4               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01     3.4              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]

# Get overview of data frame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [ ]:
print(df.dtypes)
print(type(df.dtypes))

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object
<class 'pandas.core.series.Series'>


In [ ]:
df.head(10)
type(df.head(20))

pandas.core.frame.DataFrame

In [ ]:
df.tail(20)
type(df.tail(20))

pandas.core.frame.DataFrame

In [ ]:
df.shape

(205, 26)

In [ ]:
print(list(df))
print(df.columns)

['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors', 'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']
Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')


# Data formatting - Data transformation


In [ ]:
# This approach create a new column named "city-L/100km" while keeping "city-mpg"
df["city-L/100km"] = 235 / df["city-mpg"]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

Below approach replace column "highway-mpg" with highway-L/100km    


In [ ]:
df["highway-mpg"] = 235 / df["highway-mpg"]

In [ ]:
df.rename(columns={"highway-mpg": "highway-L/100km"}, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

# Indexing

In [ ]:
print(df["bore"])
print(type(df["bore"]))

0      3.47
1      3.47
2      2.68
3      3.19
4      3.19
       ... 
200    3.78
201    3.78
202    3.58
203    3.01
204    3.78
Name: bore, Length: 205, dtype: object
<class 'pandas.core.series.Series'>


In [ ]:
print(df["bore"].values)
print(type(df["bore"].values))

['3.47' '3.47' '2.68' '3.19' '3.19' '3.19' '3.19' '3.19' '3.13' '3.13'
 '3.5' '3.5' '3.31' '3.31' '3.31' '3.62' '3.62' '3.62' '2.91' '3.03'
 '3.03' '2.97' '2.97' '3.03' '2.97' '2.97' '2.97' '3.03' '3.34' '3.6'
 '2.91' '2.91' '2.91' '2.91' '2.91' '2.91' '2.92' '3.15' '3.15' '3.15'
 '3.15' '3.15' '3.15' '3.31' '3.03' '3.03' '3.43' '3.63' '3.63' '3.54'
 '3.03' '3.03' '3.03' '3.03' '3.08' '?' '?' '?' '?' '3.39' '3.39' '3.39'
 '3.39' '3.39' '3.39' '3.76' '3.43' '3.58' '3.58' '3.58' '3.58' '3.46'
 '3.46' '3.8' '3.8' '3.78' '2.97' '2.97' '2.97' '3.03' '3.17' '3.35'
 '3.58' '3.59' '3.59' '3.35' '3.35' '3.17' '3.17' '3.15' '2.99' '3.15'
 '3.15' '3.15' '3.15' '3.15' '3.15' '3.15' '3.15' '3.33' '3.33' '3.43'
 '3.43' '3.43' '3.43' '3.43' '3.43' '3.46' '3.7' '3.46' '3.7' '3.46' '3.7'
 '3.46' '3.7' '3.46' '3.7' '3.61' '2.97' '3.03' '2.97' '2.97' '2.97'
 '3.35' '3.59' '3.94' '3.74' '3.74' '3.74' '3.94' '3.46' '3.46' '3.54'
 '3.54' '2.54' '3.54' '3.54' '3.54' '3.62' '3.62' '3.62' '3.62' '3.62'
 '3.62'

In [ ]:
print(df["bore"].index)

RangeIndex(start=0, stop=205, step=1)


In [ ]:

df["bore"][2]

'2.68'

In [ ]:
df["bore"][2] = '3'

<ipython-input-25-5ae48b8df17f>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["bore"][2] = '3'
<ipython-input-25-5ae48b8df17f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the cavea

In [ ]:
df["bore"][2]

'3'

In [ ]:
print(df["bore"].unique())
print(type(df["bore"].unique()))

['3.47' '3' '3.19' '3.13' '3.5' '3.31' '3.62' '2.91' '3.03' '2.97' '3.34'
 '3.6' '2.92' '3.15' '3.43' '3.63' '3.54' '3.08' '?' '3.39' '3.76' '3.58'
 '3.46' '3.8' '3.78' '3.17' '3.35' '3.59' '2.99' '3.33' '3.7' '3.61'
 '3.94' '3.74' '2.54' '3.05' '3.27' '3.24' '3.01']
<class 'numpy.ndarray'>


In [ ]:
df["normalized-losses"].value_counts(dropna=True)

normalized-losses
?      41
161    11
91      8
150     7
128     6
104     6
134     6
74      5
103     5
168     5
95      5
102     5
94      5
65      5
85      5
93      4
106     4
118     4
122     4
148     4
154     3
83      3
125     3
115     3
137     3
101     3
194     2
197     2
188     2
164     2
158     2
192     2
110     2
145     2
113     2
81      2
89      2
87      2
108     2
119     2
153     2
129     2
98      1
121     1
107     1
78      1
231     1
142     1
77      1
186     1
90      1
256     1
Name: count, dtype: int64

# Statistical

*   Any NaN values are automatically skipped in these statistics
*   Some statistical metrics may return "NaN," indicating missing values, and the program can’t calculate statistics for that specific data type





##statistical summary (numerical columns)

---






In [ ]:
# computes basic statistics for all numerical variable
df.describe()

symboling  wheel-base      length       width      height  \
count  205.000000  205.000000  205.000000  205.000000  205.000000   
mean     0.834146   98.756585  174.049268   65.907805   53.724878   
std      1.245307    6.021776   12.337289    2.145204    2.443522   
min     -2.000000   86.600000  141.100000   60.300000   47.800000   
25%      0.000000   94.500000  166.300000   64.100000   52.000000   
50%      1.000000   97.000000  173.200000   65.500000   54.100000   
75%      2.000000  102.400000  183.100000   66.900000   55.500000   
max      3.000000  120.900000  208.100000   72.300000   59.800000   

       curb-weight  engine-size  compression-ratio    city-mpg  highway-mpg  
count   205.000000   205.000000         205.000000  205.000000   205.000000  
mean   2555.565854   126.907317          10.142537   25.219512    30.751220  
std     520.680204    41.642693           3.972040    6.542142     6.886443  
min    1488.000000    61.000000           7.000000   13.000000    16.000000  
25%    2145.000000    97.000000           8.600000   19.000000    25.000000  
50%    2414.000000   120.000000           9.000000   24.000000    30.000000  
75%    2935.000000   141.000000           9.400000   30.000000    34.000000  
max    4066.000000   326.000000          23.000000   49.000000    54.000000

##statistical summary (all columns)

In [ ]:
df.describe(include="all")

symboling normalized-losses    make fuel-type aspiration  \
count   205.000000               205     205       205        205   
unique         NaN                52      22         2          2   
top            NaN                 ?  toyota       gas        std   
freq           NaN                41      32       185        168   
mean      0.834146               NaN     NaN       NaN        NaN   
std       1.245307               NaN     NaN       NaN        NaN   
min      -2.000000               NaN     NaN       NaN        NaN   
25%       0.000000               NaN     NaN       NaN        NaN   
50%       1.000000               NaN     NaN       NaN        NaN   
75%       2.000000               NaN     NaN       NaN        NaN   
max       3.000000               NaN     NaN       NaN        NaN   

       num-of-doors body-style drive-wheels engine-location  wheel-base  ...  \
count           205        205          205             205  205.000000  ...   
unique            3          5            3               2         NaN  ...   
top            four      sedan          fwd           front         NaN  ...   
freq            114         96          120             202         NaN  ...   
mean            NaN        NaN          NaN             NaN   98.756585  ...   
std             NaN        NaN          NaN             NaN    6.021776  ...   
min             NaN        NaN          NaN             NaN   86.600000  ...   
25%             NaN        NaN          NaN             NaN   94.500000  ...   
50%             NaN        NaN          NaN             NaN   97.000000  ...   
75%             NaN        NaN          NaN             NaN  102.400000  ...   
max             NaN        NaN          NaN             NaN  120.900000  ...   

        engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
count    205.000000          205   205     205        205.000000        205   
unique          NaN            8    39      37               NaN         60   
top             NaN         mpfi  3.62     3.4               NaN         68   
freq            NaN           94    23      20               NaN         19   
mean     126.907317          NaN   NaN     NaN         10.142537        NaN   
std       41.642693          NaN   NaN     NaN          3.972040        NaN   
min       61.000000          NaN   NaN     NaN          7.000000        NaN   
25%       97.000000          NaN   NaN     NaN          8.600000        NaN   
50%      120.000000          NaN   NaN     NaN          9.000000        NaN   
75%      141.000000          NaN   NaN     NaN          9.400000        NaN   
max      326.000000          NaN   NaN     NaN         23.000000        NaN   

        peak-rpm    city-mpg highway-mpg price  
count        205  205.000000  205.000000   205  
unique        24         NaN         NaN   187  
top         5500         NaN         NaN     ?  
freq          37         NaN         NaN     4  
mean         NaN   25.219512   30.751220   NaN  
std          NaN    6.542142    6.886443   NaN  
min          NaN   13.000000   16.000000   NaN  
25%          NaN   19.000000   25.000000   NaN  
50%          NaN   24.000000   30.000000   NaN  
75%          NaN   30.000000   34.000000   NaN  
max          NaN   49.000000   54.000000   NaN  

[11 rows x 26 columns]

## statistics for a numerical feature




In [ ]:
print(df['symboling'].count())
# .mean()excludes np.NaN values when calculating the average. Setting skipna=True (which is the default) will exclude np.NaN values, while setting skipna=False will raise an error if any np.NaN values are present.
print(df['symboling'].mean())
print(df['symboling'].std())
print(df['symboling'].min())
print(df['symboling'].max())
print(df['symboling'].quantile(0.25))
print(df['symboling'].quantile(0.5))
print(df['symboling'].quantile(0.75))

# The .unique() method is applicable to all columns, regardless of their data type. It returns an array of the unique values in the column.
print(df['symboling'].unique())

# Below line will raise error regardless of data type, we have to use mode() method instead like below line
# print(df['symboling'].top())
print(df['symboling'].mode())

# The freq() method does not exist in pandas. If you try to call it, you will get an error
# print(df['symboling'].freq())

205
0.8341463414634146
1.24530682810553
-2
3
0.0
1.0
2.0
[ 3  1  2  0 -1 -2]
0    0
Name: symboling, dtype: int64


## statistics for a categorical feature

In [ ]:
print(df['make'].count())
# print(df['make'].mean())
# print(df['make'].std())
print(df['make'].min())
print(df['make'].max())
# print(df['make'].quantile(0.25))
# print(df['make'].quantile(0.5))
# print(df['make'].quantile(0.75))

# The .unique() method is applicable to all columns, regardless of their data type. It returns an array of the unique values in the column.
print(df['symboling'].unique())

# Below line will raise error regardless of data type, we have to use mode() method instead like below line
# print(df['symboling'].top())
print(df['symboling'].mode())

# The freq() method does not exist in pandas. If you try to call it, you will get an error
# print(df['symboling'].freq())

205
alfa-romero
volvo
[ 3  1  2  0 -1 -2]
0    0
Name: symboling, dtype: int64


# Missing values


In [ ]:
df.replace('?', np.nan, inplace=True)

In [ ]:
df

symboling normalized-losses         make fuel-type aspiration  \
0            3               NaN  alfa-romero       gas        std   
1            3               NaN  alfa-romero       gas        std   
2            1               NaN  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi     3    3.47               9.0        154   
3            109         mpfi  3.19     3.4              10.0        102   
4            136         mpfi  3.19     3.4               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01     3.4              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]

In [ ]:
# used to detect missing values (np.nan, pd.NA, pd.NaT, None) in a DataFrame
# DataFrame.isnull is an alias for DataFrame.isna
df.isnull()

symboling  normalized-losses   make  fuel-type  aspiration  num-of-doors  \
0        False               True  False      False       False         False   
1        False               True  False      False       False         False   
2        False               True  False      False       False         False   
3        False              False  False      False       False         False   
4        False              False  False      False       False         False   
..         ...                ...    ...        ...         ...           ...   
200      False              False  False      False       False         False   
201      False              False  False      False       False         False   
202      False              False  False      False       False         False   
203      False              False  False      False       False         False   
204      False              False  False      False       False         False   

     body-style  drive-wheels  engine-location  wheel-base  ...  engine-size  \
0         False         False            False       False  ...        False   
1         False         False            False       False  ...        False   
2         False         False            False       False  ...        False   
3         False         False            False       False  ...        False   
4         False         False            False       False  ...        False   
..          ...           ...              ...         ...  ...          ...   
200       False         False            False       False  ...        False   
201       False         False            False       False  ...        False   
202       False         False            False       False  ...        False   
203       False         False            False       False  ...        False   
204       False         False            False       False  ...        False   

     fuel-system   bore  stroke  compression-ratio  horsepower  peak-rpm  \
0          False  False   False              False       False     False   
1          False  False   False              False       False     False   
2          False  False   False              False       False     False   
3          False  False   False              False       False     False   
4          False  False   False              False       False     False   
..           ...    ...     ...                ...         ...       ...   
200        False  False   False              False       False     False   
201        False  False   False              False       False     False   
202        False  False   False              False       False     False   
203        False  False   False              False       False     False   
204        False  False   False              False       False     False   

     city-mpg  highway-mpg  price  
0       False        False  False  
1       False        False  False  
2       False        False  False  
3       False        False  False  
4       False        False  False  
..        ...          ...    ...  
200     False        False  False  
201     False        False  False  
202     False        False  False  
203     False        False  False  
204     False        False  False  

[205 rows x 26 columns]

## 1. Remove the data

### 1.1 drop just the single data entry with the missing value

---



In [ ]:
# used to remove missing values (np.nan, pd.NA, pd.NaT, None) from a DataFrame or Series
df.dropna(axis=0)

symboling normalized-losses   make fuel-type aspiration num-of-doors  \
3            2               164   audi       gas        std         four   
4            2               164   audi       gas        std         four   
6            1               158   audi       gas        std         four   
8            1               158   audi       gas      turbo         four   
10           2               192    bmw       gas        std          two   
..         ...               ...    ...       ...        ...          ...   
200         -1                95  volvo       gas        std         four   
201         -1                95  volvo       gas      turbo         four   
202         -1                95  volvo       gas        std         four   
203         -1                95  volvo    diesel      turbo         four   
204         -1                95  volvo       gas      turbo         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   
6        sedan          fwd           front       105.8  ...          136   
8        sedan          fwd           front       105.8  ...          131   
10       sedan          rwd           front       101.2  ...          108   
..         ...          ...             ...         ...  ...          ...   
200      sedan          rwd           front       109.1  ...          141   
201      sedan          rwd           front       109.1  ...          141   
202      sedan          rwd           front       109.1  ...          173   
203      sedan          rwd           front       109.1  ...          145   
204      sedan          rwd           front       109.1  ...          141   

     fuel-system  bore  stroke compression-ratio horsepower  peak-rpm  \
3           mpfi  3.19     3.4              10.0        102      5500   
4           mpfi  3.19     3.4               8.0        115      5500   
6           mpfi  3.19     3.4               8.5        110      5500   
8           mpfi  3.13     3.4               8.3        140      5500   
10          mpfi   3.5     2.8               8.8        101      5800   
..           ...   ...     ...               ...        ...       ...   
200         mpfi  3.78    3.15               9.5        114      5400   
201         mpfi  3.78    3.15               8.7        160      5300   
202         mpfi  3.58    2.87               8.8        134      5500   
203          idi  3.01     3.4              23.0        106      4800   
204         mpfi  3.78    3.15               9.5        114      5400   

    city-mpg highway-mpg  price  
3         24          30  13950  
4         18          22  17450  
6         19          25  17710  
8         17          20  23875  
10        23          29  16430  
..       ...         ...    ...  
200       23          28  16845  
201       19          25  19045  
202       18          23  21485  
203       26          27  22470  
204       19          25  22625  

[159 rows x 26 columns]

### 1.2 drop the whole variable

In [ ]:
url = "auto.csv"
df = pd.read_csv(url)
df.replace('?', np.nan, inplace=True)
df.dropna(axis=1)

symboling         make fuel-type aspiration   body-style drive-wheels  \
0            3  alfa-romero       gas        std  convertible          rwd   
1            3  alfa-romero       gas        std  convertible          rwd   
2            1  alfa-romero       gas        std    hatchback          rwd   
3            2         audi       gas        std        sedan          fwd   
4            2         audi       gas        std        sedan          4wd   
..         ...          ...       ...        ...          ...          ...   
200         -1        volvo       gas        std        sedan          rwd   
201         -1        volvo       gas      turbo        sedan          rwd   
202         -1        volvo       gas        std        sedan          rwd   
203         -1        volvo    diesel      turbo        sedan          rwd   
204         -1        volvo       gas      turbo        sedan          rwd   

    engine-location  wheel-base  length  width  height  curb-weight  \
0             front        88.6   168.8   64.1    48.8         2548   
1             front        88.6   168.8   64.1    48.8         2548   
2             front        94.5   171.2   65.5    52.4         2823   
3             front        99.8   176.6   66.2    54.3         2337   
4             front        99.4   176.6   66.4    54.3         2824   
..              ...         ...     ...    ...     ...          ...   
200           front       109.1   188.8   68.9    55.5         2952   
201           front       109.1   188.8   68.8    55.5         3049   
202           front       109.1   188.8   68.9    55.5         3012   
203           front       109.1   188.8   68.9    55.5         3217   
204           front       109.1   188.8   68.9    55.5         3062   

    engine-type num-of-cylinders  engine-size fuel-system  compression-ratio  \
0          dohc             four          130        mpfi                9.0   
1          dohc             four          130        mpfi                9.0   
2          ohcv              six          152        mpfi                9.0   
3           ohc             four          109        mpfi               10.0   
4           ohc             five          136        mpfi                8.0   
..          ...              ...          ...         ...                ...   
200         ohc             four          141        mpfi                9.5   
201         ohc             four          141        mpfi                8.7   
202        ohcv              six          173        mpfi                8.8   
203         ohc              six          145         idi               23.0   
204         ohc             four          141        mpfi                9.5   

     city-mpg  highway-mpg  
0          21           27  
1          21           27  
2          19           26  
3          24           30  
4          18           22  
..        ...          ...  
200        23           28  
201        19           25  
202        18           23  
203        26           27  
204        19           25  

[205 rows x 19 columns]

## 2. Replacing data

### 2.1 Arbitery function

In [ ]:
url = "auto.csv"
df = pd.read_csv(url)
df.replace('?', np.nan, inplace=True)
df["normalized-losses"].fillna(666, inplace=True)

<ipython-input-12-dc75be827c04>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["normalized-losses"].fillna(666, inplace=True)


In [ ]:
df

symboling normalized-losses         make fuel-type aspiration  \
0            3               666  alfa-romero       gas        std   
1            3               666  alfa-romero       gas        std   
2            1               666  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19     3.4              10.0        102   
4            136         mpfi  3.19     3.4               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01     3.4              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]

In [ ]:
type(True)

bool

# Numpy

## Array
- The array object in numpy is called ndarray
- implicitly defined integer index used to access the values, the pandas Series has an .
- The number of dimensions of array is defined as rank
- The size of array along each dimension is defined as shape.
- can perform array-like operations

In [ ]:
ar = np.array((
    [10, 20, 30, 40]
))

In [ ]:
ar

array([10, 20, 30, 40])

In [ ]:
ar.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [ ]:
ar.index

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [ ]:
ar.shape

(4,)

In [ ]:
ar.ndim

1

In [ ]:
ar.dtype

dtype('int64')

In [ ]:
ar1 = np.array(
    [1, 12, 23, 3]
)

ar2 = np.array(
    [1, 12, 23, 3.1]
)

ar3 = np.array(
    [1, 12, 23, True]
)

ar4 = np.array(
    [1, 12, 23, 3.1, True]
)

ar5 = np.array(
    [1, "he", 23, 3]
)

ar6 = np.array(
    [1, "he", None, 3]
)

ar7 = np.array(
    [1, 1, 2+3j, 3]
)

ar8 = np.array(
    [1, 1.7, 2+3j, 3]
)

ar9 = np.array(
    [1, 1.7, 2+3j, 'you']
)

ar10 = np.array(
    [1, [1, 33], 2+3j, 'you']
)

print(ar1.dtype)
print(ar2.dtype)
print(ar3.dtype)
print(ar4.dtype)
print(ar5.dtype)
print(ar6.dtype)
print(ar7.dtype)
print(ar8.dtype)
print(ar9.dtype)
print(ar10.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
ar5[0]

np.str_('1')

In [ ]:
type(ar5[0])

numpy.str_

In [ ]:
x = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x.shape

(3, 3)

In [ ]:
x.ndim

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x[0][2]

np.int64(3)

In [ ]:
x[0, 2]

np.int64(3)

In [ ]:
x[0]

array([1, 2, 3])

In [ ]:
x[0, :]

array([1, 2, 3])

In [ ]:
x[:, 1]

array([2, 5, 8])

In [ ]:
x[x >= 8]

array([8, 9])

# Pandas

## Series
- explicitly defined index associated with the values
- can perform array-like operations

In [ ]:
ar2.dtype

dtype('float64')

In [ ]:
se = pd.Series(
    [10, 20, 30, 40]
)

In [ ]:
se

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
se.values

array([10, 20, 30, 40])

In [ ]:
se.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
se.shape

(4,)

In [ ]:
se1 = pd.Series(
    [10, 20, 30, 40],
    index=['a', 'b', 'c', 'd']
    )


In [ ]:
se1

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
type(se1)

pandas.core.series.Series

In [ ]:
se1.values

array([10, 20, 30, 40])

In [ ]:
se1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
se2 = pd.Series(
    {
     'a': 10,
     'b': 20,
     'c': 30,
     'd': 40,
     }
)

In [ ]:
se2

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
se2.values

array([10, 20, 30, 40])

In [ ]:
se2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
se3 = pd.Series([10, 20, 30, 40])
se3.index = ['a', 'b', 'c', 'd']

In [ ]:
se3

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
se4 = pd.Series(
    pd.array([10, 20, 30, 40]),
    index=['a', 'b', 'c', 'd']
)

In [ ]:
se4

a    10
b    20
c    30
d    40
dtype: Int64